# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fmxapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fmxapp

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 4.13.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  
  # Add new pods below this line
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTNetwork',
    'RCTVibration',
    'RCTSettings',
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTImage',
  ]

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'

end
