// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/antonioperez/Desktop/fmx/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/antonioperez/Desktop/fmx/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/antonioperez/Desktop/fmx/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('fmx', appParameters);
});